name: Continuous Integration / Continuous Deployment

on:
  push:
    branches: ["main", "frequency-drills"]
  pull_request:
    branches: ["main", "frequency-drills"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Run Unit Tests
      #   run: |
      #     npm install --save-dev react-dev-utils
      #     npm test -- --coverage --silent

      - name: Build
        run: |
          npm install
          npm run build


          JS=$(< "src/dist/js.txt")
          CSS=$(< "src/dist/css.txt")
          SERVICE_WORKER_FILENAME=$(< "src/dist/sw.txt")

          sed -i.bak "s/{replace-me-js}/\/book-it\/$(echo $JS | sed -r 's/\//\\\//g')/g" "src/dist/$SERVICE_WORKER_FILENAME"
          sed -i.bak "s/{replace-me-css}/\/book-it\/$(echo $CSS | sed -r 's/\//\\\//g')/g" "src/dist/$SERVICE_WORKER_FILENAME"

      # - name: Create Badges
      #   shell: bash
      #   run: |
      #     npm i -g badgen-cli
      #     export COV=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines`.split(`|`).map(k=>t[k].pct))')
      #     COLOR=$(node -p '+process.env.COV >= 95 ? `green` : `orange`')
      #     badgen -j "Test Coverage" -s $COV% -c $COLOR > build/coverage.svg

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload build folder only
          path: "src/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
